### ISSUE TITLE
IP header and reassembly

### ISSUE THREAD

**Issue by guyr** [mfontanini/libtins#225]
IPv4Reassembler creates the reassembled packet using the IP header from the last fragment.
The problem with this approach is that some IP options appear only in the first fragment and therefore will not exist in the reassembled packet.
This violates RFC 791, which assumes the IP header of the reassembled packet comes from the first fragment.

**Comment by mfontanini** [comment]
Thanks for the report! I just pushed a fix for this on the `develop` branch.

**Comment by guyr** [comment]
Hi Mattias,
I'm afraid the solution is still not correct because it assumes that the fragment that arrives first is the fragment with offset==0, but there is no such guarantee. The IP header that should be saved for reassembly is the one from the fragment with offset==0, not necessarily the first one to arrive.

**Comment by mfontanini** [comment]
Yep, you are correct. I'll fix this later today. Thanks for looking into it!
